TOPDIR ?= ../..
include $(TOPDIR)/.config

$(LEDMATRIX_SUPPORT)_SRC += services/ledmatrix/ledmatrix.c

##############################################################################
# generic fluff
# include $(TOPDIR)/scripts/rules.mk
#
include $(TOPDIR)/scripts/rules.mk

